import { Icon } from "@/components/Icon";
import { Wordmark } from "@/components/SiteNav";

/**
 * Instant shell for the project summary. The nav and the AI-generated
 * disclosure are static, so they render immediately and the disclosure is
 * on screen before any of the generated content is — which is the order the
 * guardrail in `prompts.ts` intends.
 */
function Bar({ className = "" }: { className?: string }) {
  return <div className={`rounded bg-white/5 animate-pulse ${className}`} />;
}

export default function SummaryLoading() {
  return (
    <div aria-busy="true">
      <nav
        aria-label="Project summary"
        className="sticky top-0 w-full z-50 px-6 py-4 flex justify-between items-center gap-4 bg-ink/90 backdrop-blur-md border-b border-white/5"
      >
        <div className="flex items-center gap-4">
          <Wordmark />
          <span className="h-4 w-px bg-white/10" aria-hidden="true" />
          <span className="text-sm text-gray-400">AI Project Summary</span>
        </div>
        <Bar className="h-8 w-36 rounded-full" />
      </nav>

      <div className="bg-amber-950/40 border-b border-amber-500/20 px-6 py-3 flex items-start gap-3">
        <Icon name="circle-info" className="text-amber-400 text-sm mt-0.5" />
        <p className="text-xs text-amber-300">
          <strong>AI-Generated Recommendation</strong> — This summary was
          generated by the SoftwarePros AI Architect based on your conversation.
          All requirements are estimates and require review by a Senior Software
          Architect before they become commitments.
        </p>
      </div>

      <main className="max-w-7xl mx-auto px-6 py-10 space-y-10">
        <div className="space-y-4">
          <Bar className="h-3 w-40" />
          <Bar className="h-10 w-3/4 max-w-2xl" />
          <Bar className="h-4 w-full max-w-3xl" />
          <Bar className="h-4 w-2/3 max-w-2xl" />
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {[0, 1, 2, 3].map((i) => (
            <Bar key={i} className="h-24 w-full rounded-2xl" />
          ))}
        </div>

        <div className="grid lg:grid-cols-3 gap-4">
          {[0, 1, 2, 3, 4, 5].map((i) => (
            <Bar key={i} className="h-32 w-full rounded-2xl" />
          ))}
        </div>

        <div className="space-y-3">
          <Bar className="h-3 w-32" />
          {[0, 1, 2, 3, 4].map((i) => (
            <Bar key={i} className="h-12 w-full rounded-lg" />
          ))}
        </div>
      </main>

      <p className="sr-only" role="status">
        Loading your project summary
      </p>
    </div>
  );
}
