import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faArrowRight,
  faArrowUp,
  faArrowUpRightFromSquare,
  faBars,
  faBolt,
  faBoxesStacked,
  faBrain,
  faBriefcase,
  faBug,
  faBuilding,
  faBuildingColumns,
  faCalendar,
  faCalendarCheck,
  faCertificate,
  faChartBar,
  faChartSimple,
  faCheck,
  faCircleCheck,
  faCircleInfo,
  faCircleQuestion,
  faCity,
  faClipboardCheck,
  faCloud,
  faCloudBolt,
  faCode,
  faCoins,
  faComments,
  faCreditCard,
  faCrosshairs,
  faCubes,
  faDatabase,
  faDownload,
  faEllipsis,
  faEnvelope,
  faEye,
  faFileArrowUp,
  faFileContract,
  faFileInvoiceDollar,
  faFileLines,
  faFilePdf,
  faFingerprint,
  faFolderOpen,
  faGauge,
  faGears,
  faGlobe,
  faHandHoldingHeart,
  faHeadset,
  faHeartPulse,
  faHelmetSafety,
  faIdBadge,
  faImage,
  faIndustry,
  faInfinity,
  faKeyboard,
  faLandmark,
  faLaptop,
  faLayerGroup,
  faLink,
  faListCheck,
  faLocationDot,
  faMagnifyingGlass,
  faMicrochip,
  faMicrophone,
  faMicrophoneLines,
  faMobileScreen,
  faNetworkWired,
  faPaperclip,
  faPause,
  faPlay,
  faPlug,
  faPlus,
  faPuzzlePiece,
  faQuoteLeft,
  faRobot,
  faRotateRight,
  faRoute,
  faSatelliteDish,
  faServer,
  faShareFromSquare,
  faShield,
  faShieldHalved,
  faShieldHeart,
  faSpinner,
  faStar,
  faStore,
  faTowerBroadcast,
  faTrash,
  faTriangleExclamation,
  faTruck,
  faTruckFast,
  faUmbrella,
  faUser,
  faUserSecret,
  faUserTie,
  faUsers,
  faWandMagicSparkles,
  faWaveSquare,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import {
  faGithub,
  faLinkedin,
  faXTwitter,
} from "@fortawesome/free-brands-svg-icons";

/**
 * Kebab-case icon names (as used throughout the design) mapped to the
 * Font Awesome definitions we actually bundle. Keeping this map explicit
 * means the bundle only ships icons the site uses.
 */
const ICONS = {
  "arrow-right": faArrowRight,
  "arrow-up": faArrowUp,
  "arrow-up-right": faArrowUpRightFromSquare,
  bars: faBars,
  bolt: faBolt,
  "boxes-stacked": faBoxesStacked,
  brain: faBrain,
  briefcase: faBriefcase,
  bug: faBug,
  building: faBuilding,
  "building-columns": faBuildingColumns,
  calendar: faCalendar,
  "calendar-check": faCalendarCheck,
  certificate: faCertificate,
  "chart-bar": faChartBar,
  "chart-simple": faChartSimple,
  check: faCheck,
  "circle-check": faCircleCheck,
  "circle-info": faCircleInfo,
  "circle-question": faCircleQuestion,
  city: faCity,
  "clipboard-check": faClipboardCheck,
  cloud: faCloud,
  "cloud-bolt": faCloudBolt,
  code: faCode,
  coins: faCoins,
  comments: faComments,
  "credit-card": faCreditCard,
  crosshairs: faCrosshairs,
  cubes: faCubes,
  database: faDatabase,
  download: faDownload,
  ellipsis: faEllipsis,
  envelope: faEnvelope,
  eye: faEye,
  "file-arrow-up": faFileArrowUp,
  "file-contract": faFileContract,
  "file-invoice-dollar": faFileInvoiceDollar,
  "file-lines": faFileLines,
  "file-pdf": faFilePdf,
  fingerprint: faFingerprint,
  "folder-open": faFolderOpen,
  gauge: faGauge,
  gears: faGears,
  globe: faGlobe,
  "hand-holding-heart": faHandHoldingHeart,
  headset: faHeadset,
  "heart-pulse": faHeartPulse,
  "helmet-safety": faHelmetSafety,
  "id-badge": faIdBadge,
  image: faImage,
  industry: faIndustry,
  infinity: faInfinity,
  keyboard: faKeyboard,
  landmark: faLandmark,
  laptop: faLaptop,
  "layer-group": faLayerGroup,
  link: faLink,
  "list-check": faListCheck,
  "location-dot": faLocationDot,
  "magnifying-glass": faMagnifyingGlass,
  microchip: faMicrochip,
  microphone: faMicrophone,
  "microphone-lines": faMicrophoneLines,
  "mobile-screen": faMobileScreen,
  "network-wired": faNetworkWired,
  paperclip: faPaperclip,
  pause: faPause,
  play: faPlay,
  plug: faPlug,
  plus: faPlus,
  "puzzle-piece": faPuzzlePiece,
  "quote-left": faQuoteLeft,
  radar: faSatelliteDish,
  robot: faRobot,
  "rotate-right": faRotateRight,
  route: faRoute,
  server: faServer,
  "share-from-square": faShareFromSquare,
  shield: faShield,
  "shield-halved": faShieldHalved,
  "shield-heart": faShieldHeart,
  // fa-sparkles is Pro-only; the wand variant is the closest Free equivalent.
  sparkles: faWandMagicSparkles,
  spinner: faSpinner,
  star: faStar,
  store: faStore,
  timeline: faChartSimple,
  "tower-broadcast": faTowerBroadcast,
  trash: faTrash,
  "triangle-exclamation": faTriangleExclamation,
  truck: faTruck,
  "truck-fast": faTruckFast,
  umbrella: faUmbrella,
  user: faUser,
  "user-secret": faUserSecret,
  "user-tie": faUserTie,
  users: faUsers,
  "wave-square": faWaveSquare,
  xmark: faXmark,
  // Brands
  github: faGithub,
  linkedin: faLinkedin,
  "x-twitter": faXTwitter,
} satisfies Record<string, IconDefinition>;

export type IconName = keyof typeof ICONS;

export function Icon({
  name,
  className,
  spin,
  title,
}: {
  name: IconName | string;
  className?: string;
  spin?: boolean;
  title?: string;
}) {
  const icon = ICONS[name as IconName] ?? ICONS["circle-question"];
  return (
    <FontAwesomeIcon
      icon={icon}
      className={className}
      spin={spin}
      title={title}
      aria-hidden={title ? undefined : true}
    />
  );
}
